apiVersion: 1

deleteDatasources:
  - name: TimescaleDB
    orgId: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: hgw_monitoring
    user: hgw_user
    secureJsonData:
      password: hgw_password
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: true
    isDefault: true
    editable: true
    orgId: 1