@startuml

actor Admin

boundary " Grafana" as UI
control " Backend API" as API
database "TimescaleDB" as DB

Admin -> UI : Ouvrir dashboard
UI -> API : Requête données
API -> DB : SELECT metrics
DB --> API : Résultats
API --> UI : JSON
UI --> Admin : Affichage

@enduml