@startuml

start

:Collecte métriques HGW;

:Stockage snapshots (DB);

:Planification via Airflow;

:Exécution modèles ML/DL;

:Calcul score de risque;

if (Score > seuil ?) then (Oui)
  :Créer alerte;
  :Envoyer Notifcation (Email/SMS);
else (Non)
  :Continuer surveillance;
endif

stop

@enduml